services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    volumes:
      - ./frontend:/frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:8000
  backend:
    build:

      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - ./backend/app:/app
      - ./backend/scripts:/scripts
    ports:
      - "8000:8000"
    environment:
      - DJANGO_DEBUG=True
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
